services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - media_data:/app/src/media
      - static_data:/app/src/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - media_data:/app/src/media:ro
      - static_data:/app/src/staticfiles:ro
    depends_on:
      - web

volumes:
  postgres_data:
  media_data:
  static_data:
