# Generated by Django 5.2.1 on 2025-05-11 01:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('factory_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000, message='Ano deve ter 4 dígitos.'), django.core.validators.MaxValueValidator(9999, message='Ano deve ter 4 dígitos.')])),
                ('model_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000, message='Ano deve ter 4 dígitos.'), django.core.validators.MaxValueValidator(9999, message='Ano deve ter 4 dígitos.')])),
                ('plate', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/photos/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.brand')),
            ],
        ),
    ]
